-- Ejercicio 1
select postalZip as Codigo_Postal, region as Region, country as Pais from db_autogenerated.mytable;

-- Ejercicio 2
select * from db_autogenerated.mytable
	where phone like "(811)%";

-- Ejercicio 3
select * from db_autogenerated.mytable
	where country = "Italy" or country = "Spain";

-- Ejercicio 4
select count(*) from db_autogenerated.mytable;

-- Ejercicio 5
select region as Ciudad, country as Pais, postalZip as Codigo_Postal from db_autogenerated.mytable
	where id in (select id from db_autogenerated.mytable
		where country = "Germany" or country = "Turkey");
        
-- Ejercicio 6
select min(id) as Min_Id, max(id) as Max_Id from db_autogenerated.mytable;

-- Ejercicio 7
select country as Pais, count(*) as Count_Pais from db_autogenerated.mytable
	group by country;
    
-- Ejercicio 8
select * from db_autogenerated.mytable
	order by postalZip
    limit 10;
    
-- Ejercicio 9
delete from db_autogenerated.mytable
	where country like "Singapure";
select * from db_autogenerated.mytable;
    
-- Ejercicio 10
update db_autogenerated.mytable 
	set country = "España"
	where country like "Spain"; 
select * from db_autogenerated.mytable;

